"""
ReportGenerator — formats AnalysisReport into human-readable outputs.
Supports Markdown and JSON export.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

from backend.api.schemas import AnalysisReport, BugFinding, Severity

logger = logging.getLogger(__name__)

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH:     "🟠",
    Severity.MEDIUM:   "🟡",
    Severity.LOW:      "🔵",
    Severity.INFO:     "⚪",
}


class ReportGenerator:
    """Convert an AnalysisReport into various output formats."""

    async def to_markdown(self, report: AnalysisReport) -> str:
        lines = []
        _h = lambda n, t: lines.append(f"{'#' * n} {t}")
        _nl = lambda: lines.append("")

        _h(1, "🐛 AI Bug-Fixing Assistant — Analysis Report")
        _nl()
        lines.append(f"**Report ID:** `{report.report_id}`")
        lines.append(f"**Generated:** {report.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
        if report.repo_url:
            lines.append(f"**Repository:** {report.repo_url} (branch: `{report.branch}`)")
        _nl()

        # ── Executive Summary ─────────────────────────────────────────────────
        _h(2, "Executive Summary")
        if s := report.summary:
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            lines.append(f"| Files scanned | {s.total_files_scanned} |")
            lines.append(f"| Lines scanned | {s.total_lines_scanned:,} |")
            lines.append(f"| Total bugs found | **{s.total_bugs_found}** |")
            lines.append(f"| 🔴 Critical | {s.critical_count} |")
            lines.append(f"| 🟠 High | {s.high_count} |")
            lines.append(f"| 🟡 Medium | {s.medium_count} |")
            lines.append(f"| 🔵 Low | {s.low_count} |")
            lines.append(f"| ⚪ Info | {s.info_count} |")
            lines.append(f"| Languages | {', '.join(s.languages_detected)} |")
            lines.append(f"| Analysis time | {s.analysis_duration_seconds}s |")
            _nl()

        # ── Findings grouped by severity ──────────────────────────────────────
        _h(2, "Findings")

        severity_order = [
            Severity.CRITICAL, Severity.HIGH,
            Severity.MEDIUM, Severity.LOW, Severity.INFO,
        ]
        for sev in severity_order:
            bucket = [f for f in report.findings if Severity(f.severity) == sev]
            if not bucket:
                continue
            emoji = _SEVERITY_EMOJI[sev]
            _h(3, f"{emoji} {sev.value.title()} ({len(bucket)})")
            _nl()

            for idx, bug in enumerate(bucket, 1):
                _h(4, f"{idx}. {bug.title}")
                lines.append(f"- **File:** `{bug.file_path}`")
                if bug.line_start:
                    loc = f"L{bug.line_start}" + (f"–{bug.line_end}" if bug.line_end else "")
                    lines.append(f"- **Location:** {loc}")
                lines.append(f"- **Category:** `{bug.category}`")
                lines.append(f"- **Confidence:** {bug.confidence:.0%}")
                _nl()
                lines.append(f"{bug.description}")
                _nl()

                if bug.code_snippet:
                    lines.append("**Problematic code:**")
                    lines.append("```")
                    lines.append(bug.code_snippet)
                    lines.append("```")
                    _nl()

                if bug.suggested_fix:
                    lines.append("**Suggested fix:**")
                    lines.append("```")
                    lines.append(bug.suggested_fix)
                    lines.append("```")
                    _nl()

                if bug.references:
                    lines.append("**References:**")
                    for ref in bug.references:
                        lines.append(f"- {ref}")
                    _nl()

                lines.append("---")
                _nl()

        # ── Footer ────────────────────────────────────────────────────────────
        lines.append("> *Generated by AI Bug-Fixing Assistant — results should be reviewed by a human engineer.*")

        return "\n".join(lines)
